Add plone 5 profiles
4teamwork/ftw.redirector pull request #10
Opened 2019-09-26 13:22 UTC by djowett-ftw

I'm not sure we want to do the last commit (429e24287), but confident of the rest of it.

@jone Btw The idea of adding a `to_plone5` profile (prob without ftw.upgrade) seems more attractive to me today (but I've not done it yet)

2019-09-26 15:49 UTC, jone requested changes
- I'm also not sure about the impact of the last commit; I'm not too familiar yet with the new registry. But no objection if it works 😉 
- Do we need to update classifiers / readme / changelog?

2019-09-26 15:49 UTC, jone commented on ftw/redirector/profiles/uninstall_plone5/registry.xml
> +             interface='Products.CMFPlone.interfaces.IResourceRegistry'
```suggestion
             interface="Products.CMFPlone.interfaces.IResourceRegistry"
```

2019-09-26 15:49 UTC, jone commented on ftw/redirector/profiles/uninstall_plone5/registry.xml
> +             interface='Products.CMFPlone.interfaces.IBundleRegistry'
```suggestion
             interface="Products.CMFPlone.interfaces.IBundleRegistry"
```

2019-09-27 08:37 UTC, djowett-ftw commented
I reverted the last commit as it stops the CSS being minified (de-whitespaced) within `logged-in.css` - and while that doesn't matter much here as there's just 7 rules - it's a good principle for elsewhere.

doc changes made as requested. Plone 5.1 classifier is already there.

will rebase (and squash where appropriate before merge)

2019-09-30 14:53 UTC, jone approved these changes
👍

2019-10-01 08:30 UTC, merged